vich_uploader:
    db_driver: orm

    mappings:
       Apprenant_image:
            uri_prefix: /uploads/brochures
            upload_destination: '%kernel.project_dir%/public/uploads/brochures'
            namer: Vich\UploaderBundle\Naming\UniqidNamer